// Mocks generated by Mockito 5.4.6 from annotations
// in artlens/test/shared/data/repository/art_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:artlens/shared/data/model/artworks_response_dto.dart' as _i5;
import 'package:artlens/shared/data/source/local/app_database.dart' as _i7;
import 'package:artlens/shared/data/source/local/artwork/artwork_dao.dart'
    as _i6;
import 'package:artlens/shared/data/source/local/category/category_dao.dart'
    as _i8;
import 'package:artlens/shared/data/source/remote/remote_art_datasource.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:retrofit/retrofit.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeHttpResponse_0<T> extends _i1.SmartFake
    implements _i2.HttpResponse<T> {
  _FakeHttpResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [RemoteArtDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoteArtDatasource extends _i1.Mock
    implements _i3.RemoteArtDatasource {
  MockRemoteArtDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.HttpResponse<_i5.ArtworksResponseDto>> retrievePage(
    String? includedFields,
    int? page,
    int? limit,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#retrievePage, [includedFields, page, limit]),
            returnValue:
                _i4.Future<_i2.HttpResponse<_i5.ArtworksResponseDto>>.value(
                  _FakeHttpResponse_0<_i5.ArtworksResponseDto>(
                    this,
                    Invocation.method(#retrievePage, [
                      includedFields,
                      page,
                      limit,
                    ]),
                  ),
                ),
          )
          as _i4.Future<_i2.HttpResponse<_i5.ArtworksResponseDto>>);
}

/// A class which mocks [ArtworkDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockArtworkDao extends _i1.Mock implements _i6.ArtworkDao {
  MockArtworkDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i7.ArtworkEntity>> retrievePage(int? offset, int? limit) =>
      (super.noSuchMethod(
            Invocation.method(#retrievePage, [offset, limit]),
            returnValue: _i4.Future<List<_i7.ArtworkEntity>>.value(
              <_i7.ArtworkEntity>[],
            ),
          )
          as _i4.Future<List<_i7.ArtworkEntity>>);

  @override
  _i4.Future<void> insertAll(List<_i7.ArtworkEntity>? entities) =>
      (super.noSuchMethod(
            Invocation.method(#insertAll, [entities]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [CategoryDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockCategoryDao extends _i1.Mock implements _i8.CategoryDao {
  MockCategoryDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<Map<int, List<_i7.CategoryEntity>>> retrieveCategoriesForArtworks(
    List<int>? artworkIds,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#retrieveCategoriesForArtworks, [artworkIds]),
            returnValue: _i4.Future<Map<int, List<_i7.CategoryEntity>>>.value(
              <int, List<_i7.CategoryEntity>>{},
            ),
          )
          as _i4.Future<Map<int, List<_i7.CategoryEntity>>>);

  @override
  _i4.Future<void> insertArtworksCategories(
    Map<int, List<_i7.CategoryEntity>>? artworkCategories,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#insertArtworksCategories, [artworkCategories]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
